spring:
  data:
    mongodb:
      host: ${MONGO_HOST:mongo}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:resume_screening_db}

    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

    elasticsearch:
      uris: ${ES_URI:http://elasticsearch:9200}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

logging:
  level:
    com.resumeai: INFO
